[package]
name = "actix-example"
version = "0.0.1"
authors = ["Naoki Sawada"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = "1.0.117"
log = "0.4.0"
env_logger = "0.8.1"
derive_more = "0.99.11"
actix-web-httpauth = "0.5.0"
